# Generated by Django 3.0 on 2020-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_hyperlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='hyperlink',
            new_name='url',
        ),
    ]
