# Generated by Django 3.0 on 2020-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_multiplechoicecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='multiplechoicecard',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=6),
        ),
        migrations.AlterField(
            model_name='multiplechoicecard',
            name='url',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
